# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25e991ada40c6a60117a97c7d40838e5ce9572a52e7ca3011d6faf152d77c077ca624ef1e35fda43fcdc134133fac5f0ccf9eafaba0055957e3136dae2305bf2

test:
  secret_key_base: 6421481bbb2dfbc65f2eb91a41cad0d5b5cf3a4c0c2c01c22281a8883e0441ca2314fd8249ba0fe465480257bbe3a3a16122cad92fdd13f951a472e7a1ea7019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
